
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app_name }}-blue"
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app_name }}
    version: blue
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 80 }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app_name }}-green"
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app_name }}
    version: green
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 80 }}
      protocol: TCP